- README.rst
> Fixes a typo

- transcrypt/demos/riot_demo/.gitignore
- transcrypt/demos/riot_demo/README.md
- transcrypt/demos/riot_demo/riot_demo.html
- transcrypt/demos/riot_demo/riot_tag.py
- transcrypt/demos/riot_demo/sample2_tag.py
- transcrypt/demos/riot_demo/tags/sample.js
- transcrypt/demos/riot_demo/tags/sample.tag
Added a Demo for RiotJS. Would be glad if you could consider including it into Transcrypt.
And... DANKEWELL FOR THIS *AMAZING* TOOL!!
> Riotjs demo

- transcrypt/development/continuous_integration/README.md
> better readme

- transcrypt/development/automated_tests/transcrypt/autotest.py
- transcrypt/development/automated_tests/transcrypt/callable_test/__init__.py
- transcrypt/modules/org/transcrypt/__javascript__/__builtin__.mod.js
Hi, 
This PR adds unit tests and an implementation for the  `callable` method. Please let me know if you have any questions or comments. As discussed I've tried to keep the syntax formatting in the __builtin__.mod.js file the same as the existing code - let me know if I missed anything.
> Implementation for `callable` built-in function

- transcrypt/development/automated_tests/transcrypt/dictionaries/__init__.py
- transcrypt/modules/org/transcrypt/__javascript__/__builtin__.mod.js
Hi, 
This PR fixes some bugs in the dict object creation and methods. This is primarily focused on fixing the bug in Issue #221 but after creating some additional unit tests, I found that there are some other issues that needed fixing. 
Please note, that this PR addresses dict creation on objects that are not using `Map` because these are not tested in Travis CI or `test_server.py` yet. We will need to adapt these changes to cover both cases. If you would like to wait on this PR until these fixes are incorporated to both variants please let me know.  
Additionally, this PR contains a commit addressing inconsistencies in the js for `__builtin__.mod.js` with respect to semicolons.
> Fix for Issue #221 - Dict Creation and other Bugs

- transcrypt/development/automated_tests/re/basictests.py
- transcrypt/modules/re/__init__.py
- transcrypt/modules/re/translate.py
Fixes issues with the re module:
- Named capture groups after the first had wrong index
- The "default value" argument to `match.groups()` didn't work (I also added a test for it)
> Regex fixes

- transcrypt/development/continuous_integration/test_server.py
test flags did not work.
I now committed the -e 6 flags as well RESULTING IN BROKEN TRAVIS
> test flags should now work

- .travis.yml
- transcrypt/development/continuous_integration/run
Hi, the tests did sometimes not finish on travis, hanging in the cleanup routine which is anyway not required on travis. So I added a switch for run to NOT cleanup, which i set in .travis.yml.
> No process kills on travis

- transcrypt/modules/warnings/__init__.py
This commit adds some final docs and cleanup to the warnings module. This module has some limitations but I think it is sufficient to provide the necessary baseline features. I propose closing issue #191 with this commit.
> modules:warnings: Updated documentation and comments about usage.

- transcrypt/modules/math/__init__.py
Hoping this is formatted / completed correctly.
I found isNaN at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN, it seems to be widely available.
> Add math.isnan()

- transcrypt/demos/cyclejs_demo/README.md
- transcrypt/demos/cyclejs_demo/component_demos/isolated_bmi_slider/bmi.html
- transcrypt/demos/cyclejs_demo/component_demos/isolated_bmi_slider/bmi.py
- transcrypt/demos/cyclejs_demo/component_demos/isolated_bmi_slider/components/labeled_slider.py
- transcrypt/demos/cyclejs_demo/component_demos/isolated_bmi_slider/components/snabbdom.py
- transcrypt/demos/cyclejs_demo/component_demos/labeled_slider/labeled_slider.html
- transcrypt/demos/cyclejs_demo/component_demos/labeled_slider/labeled_slider.py
- transcrypt/demos/cyclejs_demo/component_demos/labeled_slider/labeled_slider_js_orig.js
- transcrypt/demos/cyclejs_demo/component_demos/labeled_slider/snabbdom.py
- transcrypt/demos/cyclejs_demo/cyclejs_demo.html
- transcrypt/demos/cyclejs_demo/cyclejs_demo.py
- transcrypt/demos/cyclejs_demo/cyclejs_http_demo.html
- transcrypt/demos/cyclejs_demo/cyclejs_http_demo.py
Hi Jacques, this is just a set of new demos for a new js framework which many people consider very relevant.
> New Demo: CycleJS

- transcrypt/docs/sphinx/installation_use.rst
This looks like an awesome project!
> fix misspelling of transcrypt

- README.rst
* validate and update README.rst using @mgedmin restview --pypi-strict 
Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>
> Ensure that ReST long_description displays well on Pypi

- README.rst
> update documentation link to canonical URL

- transcrypt/modules/org/transcrypt/__javascript__/__builtin__.mod.js
Presumably a small typo in the last letter
> Fix __all__.org = ord to __all__.ord = ord

- transcrypt/development/continuous_integration/bottle.py
- transcrypt/development/continuous_integration/run
- transcrypt/development/continuous_integration/test_server.py
Using the `dev` version of bottle just because I copied it straight from github. It works, so no worries.
Also, I just "fixed" the `test_server.py` script without getting into detail as to why it needs to `reload` the `sys` module (it most probably does not). Again, it works in python `3.x` just fine.
> Update bottle to 0.13-dev, use python3 in run and test_server

- transcrypt/development/automated_tests/transcrypt/autotest.py
- transcrypt/development/automated_tests/transcrypt/method_and_class_decorators/__init__.py
- transcrypt/modules/org/transcrypt/__javascript__/__core__.mod.js
- transcrypt/modules/org/transcrypt/compiler.py
Here are the changes to allow method, classmethod, staticmethod decorators for Transcrypt. There are still too few tests, but as they do not change old behavior, I think we can merge them.
> Method decorators

- transcrypt/development/automated_tests/transcrypt/autotest.py
- transcrypt/development/automated_tests/transcrypt/method_and_class_decorators/__init__.py
- transcrypt/modules/org/transcrypt/compiler.py
Implemented simple property decorator setter:
```python
@property
def my_property(self):
return self.prop
@my_property.setter
def my_property(self, value):
self.prop = value
```
> Property decorator setter implementation

- transcrypt/development/automated_tests/transcrypt/autotest.py
- transcrypt/development/automated_tests/transcrypt/module_datetime/__init__.py
- transcrypt/modules/datetime/__init__.py
More testing needed. If you found some errors, I will fix them.
> datetime module

- transcrypt/development/automated_tests/transcrypt/classes/__init__.py
- transcrypt/modules/org/transcrypt/__javascript__/__builtin__.mod.js
Also fixed isinstance bug when checking primitives with `object` argument.
> issubclass implementation

- transcrypt/demos/terminal_demo/terminal_element.html
- transcrypt/demos/terminal_demo/terminal_element.min.html
- transcrypt/demos/terminal_demo/terminal_element.py
- transcrypt/docs/sphinx/integration_javascript.rst
Hi,
I've struggled a little bit with using the __terminal__ DOM element. This PR improves this part of the documentation to help other users.
Regards,
Carsten
> Extend usage documentation of the __terminal__ DOM element

- transcrypt/development/automated_tests/re/basic_jsre.py
- transcrypt/development/automated_tests/re/basic_pyre.py
- transcrypt/development/automated_tests/re/basictests.py
- transcrypt/modules/re/__init__.py
- transcrypt/modules/re/translate.py
I decided to rewrite the py2js regex translator from scratch, because my original code was not very good. It's nearly done, but needs some more tests , bug fixes, and cleanup.
Where should the documentation for the re module go? There are some limitations and Transcrypt specific features (notably, the option to use a JS-regex directly instead of using the translation step)  that the user should know about.
> [WIP]  Re module

- transcrypt/modules/math/__init__.py
> added copysign

- transcrypt/development/automated_tests/transcrypt/autotest.py
- transcrypt/development/automated_tests/transcrypt/module_unicodedata/__init__.py
Added the autotests for unicodedata.normalize(). See #548.
> Add autotests for module unicodedata.

- transcrypt/modules/org/transcrypt/compiler.py
Generates wrapping function with accumulator to avoid accidental double function calls.
Example Python:
```python
x(y).lower()
```
Resulted before patch (faulty code!) in:
```javascript
__call__ (__call__ (x, null, y).lower, __call__ (x, null, y));
```
Results now in:
```javascript
(function () {
var __accu0__ = __call__ (x, null, y);
return __call__ (__accu0__.lower, __accu0__);
}) ();
```
> Fix for opov pragma on attribute function-calls

- transcrypt/docs/sphinx/special_facilities.rst
Fixed some typos I've come across reading the documentation about pragmas.
> Documentation fixes

- transcrypt/modules/re/translate.py
Closes #400 
@JdeH let me know if the message is correct
> Add exception message to max iteration error in re translation

- .travis.yml
> Revert "Travis CI: The sudo tag is now deprecated in Travis"

- transcrypt/demos/react_demo/react_demo.html
- transcrypt/demos/react_demo/react_demo.py
- transcrypt/modules/org/reactjs/__init__.py
- transcrypt/modules/org/reactjs/dom.py
Since React proposes [hooks](https://reactjs.org/docs/hooks-intro.html) as the preferred way of writing new components, I've tried to rewrite React Demo using hooks. This looks considerably cleaner than createClass-based implementation.
Also I took liberty of creating `org.reactjs` package with some additions to allow the use of hooks as decorators.
> React Demo with hooks
