TranscryptOrg/Transcrypt

transcrypt/modules/org/transcrypt/__javascript__/__builtin__.mod.js

Update builtin.mod.js : add String.prototype.getslice
Allow string slicing:
```
s='abcdefghij'
print(s[2:3])
print(s[:3])
print(s[2:])
print(s[::2])
```

Add string slicing

---

transcrypt/development/continuous_integration/run

This PR targets Issue #171 
I've added code to capture the PGID of the XVFB process group, PID of the test server, and code that kills these child processes when the script has completed. I've also had a handler for Ctl-C so that if the user attempts to kill the hung process the children get cleaned up properly.

Gracefully Kill Children of CI run script

---

transcrypt/__main__.py
transcrypt/modules/org/transcrypt/autotester/__init__.py

This PR is intended to address Issue #184 
In the PR, I've also added a small commit to generate an exception traceback in when transcrypt attempts to run the passed source in python. Without this traceback it is quite near impossible to debug what the problem is. 
The major portion of this PR is a commit refactoring the auto test HTML generation. This  adds the new table view concept. See the attached images.
This PR also adds some code to capture any exceptions that are generated by any of the testlets and it will attempt to show the stacktrace for that exception if it exists. Currently this won't capture exceptions coming from the JS runtime, but it will capture exceptions coming from the python code. This is just base line feature right now. 
The table formatting of the generated …

Autotestbrowsermod

---

transcrypt/development/continuous_integration/run

OK - very sorry about this but I think there was a small bug introduced into the last refactor. It was not capture the XVFB PID appropriate which caused it achieve the desired function. This patch should fix that.

Fixed a bug introduced in the last refactor of the run script.

---

transcrypt/modules/org/transcrypt/autotester/__init__.py

Hi, 
As we discussed in the last PR for the autotester browser view, the latest HTML generation has a couple of short comings: 
1. Lack of ability to quickly search for tests with errors ("!!!" prefix missing)
2. Ability to expand/contract portions of the table
This PR fixes both of these short comings. I currently have it setup to collapse by default any module where all tests successfully completed. The user can then expand or collapse by clicking on the blue header for that module. 
Note that the code in this file is getting pretty spaghetti-like. It could use a code cleanup but for right now I don't want to spend any more time on it.

Autotester Browser View Update #2

---

transcrypt/development/automated_tests/re/autotest.py
transcrypt/development/automated_tests/re/basic_jsre.py
transcrypt/development/automated_tests/re/basic_pyre.py
transcrypt/development/automated_tests/re/basictests.py
transcrypt/modules/org/transcrypt/__javascript__/__builtin__.mod.js
transcrypt/modules/org/transcrypt/__standard__.py
transcrypt/modules/org/transcrypt/autotester/__init__.py
transcrypt/modules/re/__init__.py
transcrypt/modules/re/re.py
transcrypt/modules/re/translate.py

Hi, 
The primary thrust of this PR is to address issue #98 - the python re module. This PR also contains a few commits that update the autotester code base. The most important of these is a bug fix that corrects an error in the autotester where false positives were possible if a test suite contained only a single module and had an exception. Additionally, there is a single commit that fixes the KeyError exception (it was in \_\_standard\__.py but not in \_\_builtin__.js) and adds new exceptions from the standard builtin exceptions list to support the re module.
For the Python regular expressions module, I've taken the approach discussed in the Issue #98. The re module has two modes that can be controlled via a flag. The first mode translates python re syntax into javascript syntax and …

Initial Regular Expression Integration

---

transcrypt/development/automated_tests/logging/autotest.py
transcrypt/development/automated_tests/logging/logger_tests.py
transcrypt/modules/logging/__init__.py
transcrypt/modules/logging/config.py
transcrypt/modules/logging/handlers.py

This commit includes an initial implementation of the logging module and addresses Issue #174. It
includes a basic unit test for the logger only. The `logging.basicConfig`
and `logging.config.dictConfig` methods are not tested at this point.
I've stubbed in placeholders for some additional logging.Handler objects
that I think could be useful in the future but these are not tested
yet.
The provided unit test inserts a new TestHandler object that calls the AutoTester `check` method. Part of the tests also inserts a StreamHandler and allows manual inspection of the console.log but I haven't thought of a good way to test that other than manually.

modules: Initial implementation of the `logging` python module

---

transcrypt/development/automated_tests/transcrypt/autotest.py
transcrypt/development/automated_tests/transcrypt/reprtest/__init__.py
transcrypt/modules/org/transcrypt/__javascript__/__builtin__.mod.js

This commit fixes an issue with the `repr` builtin function that was causing the represented strings not to show value values when None or null values were present. This issue triggered the finding of a couple of other issues that have subsequently been fixed by using a recursive call to `repr()`

Fix Repr Issue #181

---

transcrypt/modules/org/transcrypt/compiler.py

Hi, 
This PR builds on the work for `__file__` and `__line__`. This adds a compile-time replacement macro for `__name__` to insert the module name like in python. 
Additionally, this adds a `__filename__` macro that includes the name of the file without the absolute path. The `__filename__` macro will include the subdirectory if the filename starts with `__init__` because I don't think that `__init__.py` would be useful to anyone.

__name__ and __filename__ macro features

---

transcrypt/development/automated_tests/logging/autotest.py
transcrypt/development/automated_tests/logging/basicConfig_tests.py
transcrypt/development/automated_tests/logging/buffering_tests.py
transcrypt/development/automated_tests/logging/config_tests.py
transcrypt/development/automated_tests/logging/logger_tests.py
transcrypt/development/automated_tests/logging/utils.py
transcrypt/modules/logging/__init__.py
transcrypt/modules/logging/config.py
transcrypt/modules/logging/handlers.py
transcrypt/modules/re/__init__.py

This PR contains updates to the the `logging` module to add basic functionality for `basicConfig` and `dictConfig`. I've added basic unit tests for these features and I've additionally added some unit tests for the buffering handlers.
This PR also contains a minor update to the `re` module to update it to the latest support of `callable` which wasn't available earlier.
This commit primarily addresses issue #174

Logging Config Baseline Implementation

---

transcrypt/development/manual_tests/module_logging/README.md
transcrypt/development/manual_tests/module_logging/ajaxlogclient.html
transcrypt/development/manual_tests/module_logging/ajaxlogclient.py
transcrypt/development/manual_tests/module_logging/ajaxlogserver.py
transcrypt/modules/logging/config.py
transcrypt/modules/logging/handlers.py

This PR contains an update to the AJAX logging handler and a manual test for checking this feature. I've also made the converter syntax throw `NotImplementedError` as discussed because this code in `logging.config` is not well tested. 
I think this commit completes the basic necessities for the logging module and closes issue #174 . There are probably bugs and things we will have to fix but I think this gets us to a point where we can at least start testing it.

Manual test for AJAX handler and cleanup of config

---

transcrypt/modules/org/transcrypt/compiler.py

This adds a special case to the "If" visitor for when the 'orelse' statement list only contains another single 'If' statement.
Take this source code, for example:
```
if a:
print('a')
elif b:
print('b')
elif c:
print('c')
elif d:
print('d')
elif e:
print('e')
elif f:
print('f')
elif g:
print('g')
```
Without this patch, Transcrypt creates the following:
```
if (a) {
print ('a');
}
else {
if (b) {
print ('b');
}
else {
if (c) {
print ('c');
}
else {
if (d) {
print ('d');
}
else {
if (e) {
print ('e');
}
else {
if (f) {
print ('f');
}
else {
if (g) {
print ('g');
}
}
}
}
}
}
}
```
With this patch, it would instead create:
```
if (a) {
print ('a');
}
else if (b) {
print ('b');
}
else if (c) {
print ('c');
}
else if (d) {
print ('d');
}
else if (e) {
print ('e');
}
else if (f) {
print ('f'); …
```

Make prettier 'else if' JavaScript statements

---

transcrypt/modules/org/transcrypt/compiler.py

'global' is a valid symbol in JavaScript, but not python. Add 'js_global' as an alias to 'global' to allow for accessing this.

Add js_global to aliases

---

transcrypt/development/automated_tests/transcrypt/modules/__init__.py
transcrypt/development/automated_tests/transcrypt/modules/mod4.py
transcrypt/development/automated_tests/transcrypt/modules/mod5.py
transcrypt/modules/org/transcrypt/compiler.py

This should fix #269. As a side affect, this also allows cyclical imports to work correctly when one of the imports is done inside of a function.

Fix `from x import y` inside functions.

---

.gitignore
transcrypt/modules/org/transcrypt/__javascript__/__builtin__.mod.js

This pull request should fix an issue with zipping characters of a string with other lists, see #326 (second comment.)
The zip function was only checking if the first argument was a string and splitting it in that case. This meant that if the first argument was e.g. a list of integers and the second was the string 'abc', (as in the case of `enumerate('abc')`), the zip function didn't work. The patch splits all arguments to zip that are strings.
Includes a minor fix for .gitignore, where my `egg-info` was not being ignored by git.

Fix zip function when zipping characters of a string with another list

---

.gitignore

When you experiment with transcrypt, its repo quickly gets more and more autogenerated things. This is an attempt to tighten up the `.gitignore` file slightly so as to reduce the amount of noise in `git status`
Refs: https://github.com/QQuick/Transcrypt/issues/342

Add more (automatically generated) places to .gitignore

---

transcrypt/development/automated_tests/__future__/autotest.py
transcrypt/development/automated_tests/__future__/division.py
transcrypt/development/automated_tests/__future__/generators.py
transcrypt/development/automated_tests/__future__/nested_scopes.py
transcrypt/development/automated_tests/__future__/print_function.py
transcrypt/development/automated_tests/__future__/unicode_literals.py
transcrypt/development/automated_tests/__future__/with_statement.py

Here are some promised tests for the `__future__` module that you merged earlier. (This PR message is a superset of the commit message). I am using the `0.13-dev` version of bottle (and still haven't figured out/don't want to figure out how to run two pythons in one virtual environment), so we will have to see if this tests pass CI on current `2.x` and `0.12.9` Travis (I've checked them locally on `0.13-dev` with `3.6.1` python)
The two things that I could not make to work in tests: byte strings with `b'Hello, world!` syntax and the `with` statement with the custom simple context manager. I left them commented out. Any thoughts?
Add simple tests for these features:
- division
- generators
- nested_scopes
- print_function
- unicode_literals
Tests that need attention:
- byte strings in …

Add tests for transcrypt module __future__

---

transcrypt/development/automated_tests/transcrypt/module_builtin/__init__.py
transcrypt/modules/org/transcrypt/__javascript__/__builtin__.mod.js

- isalnum
- isalpha
- isdecimal
- isdigit
- islower
- isupper
- isspace
- isnumeric (*)
These methods are *not* entirely compatible with CPython because they
deal with ascii characters only, not general unicode. Also, isnumeric
existed before and it is even less compatible: it allows floats, which
python does not.
I have also tried adding some tests but it did not work for me:
I navigated to `automated_tests/transcrypt`, compiled the tests with these two commands:
```
transcrypt -c -da autotest.py
transcrypt -r -c -da autotest.py
```
After that, I opened `autotest.html` and it showed me an empty table.

Add some of the string methods:

---

transcrypt/development/automated_tests/inspect/autotest.py
transcrypt/development/automated_tests/inspect/test_isclass.py
transcrypt/development/continuous_integration/set1
transcrypt/modules/inspect/__init__.py

Currently the javascript version returns `False` for everything (class, function or whatever) while python version, obviously, returns `False` for everything except a class, when in returns `True`. See test.
Any idea why `isclass` does not work?
Update: I copied its implementation [from cpython](https://github.com/python/cpython/blob/af5392f5c6f8014659e995840df6ee7b5017f743/Lib/inspect.py#L73).

Add inspect.isclass and tests for it

---

LICENSE

Added it directly via GitHub. When adding a file named license, github offers it's list of inherently supported ones. This also creates the little sign on the upper right to help people know it's all good :)

Apache 2.0 license file

---

transcrypt/development/automated_tests/transcrypt/truthyness/__init__.py
transcrypt/modules/org/transcrypt/__javascript__/__builtin__.mod.js

This improves compatibility and allows more fine-grained truth-value
testing control for python classes.
Closes #375 
There are more tests and the old tests pass locally, let's look at what CI has to say.
Update: and CI passes, bingo!

Make __t__ respect __bool__ and __len__ like Python does

---

transcrypt/development/automated_tests/transcrypt/general_functions/__init__.py
transcrypt/modules/org/transcrypt/__javascript__/__builtin__.mod.js

I've also added a couple of tests for the `len` function. Notably, it is still rather different from the `len` in Python: it does not throw errors for things that "do not have a length", like numbers, `None` or whatever. However, such fine-grained compatibility is not necessary. What is necessary, in my opinion, is to use `__len__` when the object has it.

Make function len call __len__ (from Python) if it exists

---

transcrypt/modules/org/transcrypt/__javascript__/__builtin__.mod.js
transcrypt/modules/org/transcrypt/__standard__.py

I believe this better matches Python's default behavior. 
This commit removes default `"Erroneous Value"` and `"Invalid Key"` messages for `ValueError` and `KeyError` respectively. These do not match Python's behavior, and prevent more custom messages from being passed in.
This commit also updates usages of ValueError and KeyError in `__builtin__` to use individual strings which match python3.5's error messages rather than using the defaults that are now removed.
I don't know if any end-user code relies on these messages, but this could be changed to keep `"Erroneous Value"` and `"Invalid Key"` messages as default if none are supplied. I chose to have `""` as the default message in order to match Python 3.5's behavior, but that's not as essentially useful as allowing customizable messages …

Remove default messages for ValueError and KeyError

---

transcrypt/modules/org/transcrypt/compiler.py

Fixed decorator name checking when importing from another module with parameters:
```python
@a_module.b_module.my_decorator('param1')
def my_function():
...
```

Decorator fix

---

transcrypt/modules/org/transcrypt/__javascript__/__builtin__.mod.js
transcrypt/modules/org/transcrypt/compiler.py

A possible method for avoiding the overhead of `__call__` on overloaded operators.  Adds an optional argument that does a compile-time swap for the pythonic overload methods instead of the full call search.  So where this python:
__pragma___('opov')
a += b
__ pragma__ ('noopov')
generates this JS:
var a= __call__ (__iadd__, null, a, b);
with the change this version:
__pragma___('opov', 'fast')
a += b
__ pragma__ ('noopov')
generates
a.__iadd__(b)
The intent would be to use this fairly narrowly in performance sensitive code.  
As written the following would fail if the left-hand operand does not have the correct magic methods.  For user code (especially pythong) that seems fine; it's an annoyance for native types.   However adding the magic methods to `Number.prototype` works, although I …

example support for lexical operator overloading mode

---

transcrypt/modules/org/transcrypt/compiler.py

The xtrans pragma currently uses subprocess/shlex for running external transpilers.
Using shlex.split for subprocess under Windows is broken.
Luckily, it is also not necessary in that case.
https://stackoverflow.com/a/35900070

Do not use shlex.split under Windows

---

transcrypt/modules/org/transcrypt/compiler.py
transcrypt/modules/org/transcrypt/utils.py

A command line switch can be used rather than defining it in the call each time.
Resolves issue #506

Command line switch to define the shell command to be used in xtrans calls.

---

transcrypt/modules/org/transcrypt/compiler.py

Fixes issue: https://github.com/QQuick/Transcrypt/issues/514

Implement a builtin alias of 'js_default' -> 'default'

---

transcrypt/modules/org/transcrypt/compiler.py
transcrypt/modules/org/transcrypt/utils.py

I've found that I sometimes want to do a pep-8-ificiation on an external JS library so my code is consistent  from end to end, but managing the large number of aliases involved manually is very hairy.
This allows the user to specify one or more alias files from the compiler command line, and activate/deactivate them using the alias pragma.  A single-argument pragma is assumed to be a file name when adding aliases, and for noalias specifying the file name again removes all aliases which emanate from it.
__pragma___('alias', 'myaliasfile')
item.this_is_an_alias ("defined in myaliasfile")
__pragma__('noalias', 'mayaliasfile') 
Alias files can live anywhere on the module search path.
I've found this convenient, though it would be particularly nice to make the aliases part of the module …

Add support for reading aliases from textfiles

---

transcrypt/modules/org/transcrypt/compiler.py

Main discussion in #528.
Proposal is to cover for both:
1. JavaScript (ES6): [`Object.is()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is) method
1. jQuery `.is()`: [jQuery docs](http://api.jquery.com/is/), [w3schools docs](https://www.w3schools.com/jquery/traversing_is.asp)
Other line change is a minor typo fix.

Provide predefined alias for `.is()` #528

---

transcrypt/modules/unicodedata/__init__.py

Let me know if there's a way I can add automated tests for this module!
Here's a simple test for this function:
```python
from unicodedata import normalize
assert normalize('NFC', '\u00e9') == normalize('NFC', 'e\u0301'))
```
Addresses #547

[WIP] Add unicodedata.normalize()

---

transcrypt/modules/org/transcrypt/autotester/html.py

Should address trying to run autotest on systems where the default encoding is *not* UTF-8.

Explicitly open autotest.html in UTF-8.

---

transcrypt/modules/org/transcrypt/__builtin__.js

For step=1, the common case, performing a native array slice should be faster than copying the elements ourselves.
I'm not sure how to profile to tell whether it actually is, but it seems like it could be a good idea.
Let me know what you think, and whether there's anything else I can do in this PR. I'm not 100% familiar with the structure nowadays and I'm not sure whether anything needs to be done for pre-ES6 compatibility here?

Use JavaScript Array.slice in '__getslice__' when applicable

---

transcrypt/modules/org/transcrypt/compiler.py

Reverts QQuick/Transcrypt#561
This code seems to work fine, but I have the impression that there is some unneeded code dupplication.
Will create a different branch for this and merge it there to have another good look at it.

Revert "Fix for opov pragma on attribute function-calls"

---

transcrypt/modules/org/transcrypt/compiler.py

This should be purely a output-code-niceness improvement.
`list()` currently just runs `Array.from`, so it seems redundant if we've already just created a fresh list using `[]` syntax. I don't believe it will have any affect other than just having another function run every time a list is instantiated.

Remove generation of 'list()' around list literals

---

transcrypt/modules/org/transcrypt/utils.py

Currently, Transcrypt reports something like
```
Error while compiling (offending file last):
File '<unknown>', line 32, at import of:
File '<unknown>', line 4, at import of:
File '<org.transcrypt.compiler.Module object at 0x7f89eb64fda0>', line 4, namely:
```
this fixes it so that
```
Error while compiling (offending file last):
File '/home/user/game/game.py', line 32, at import of:
File '/home/user/game/html5/__init__.py', line 4, at import of:
File '<org.transcrypt.compiler.Module object at 0x7fd6746f6c50>', line 4, namely:
```
will be reported.

Corrected sourcePath info in Errors

---

transcrypt/modules/org/transcrypt/__runtime__.py

Not 100% sure this is a change that wants to be made, but opening this PR just in case.
This should let all errors that inherit from `Exception` have stack traces, even if no error is passed into the constructor. The stack traces will be a bit longer since they'll include `Exception.__init__` itself, but I think they should still be useful?
This is just another change I was working with that I'm not 100% sure if it makes sense to make in transcrypt itself.

Create an error to get a stacktrace if an error isn't passed into Exception.__init__

---

.travis.yml

__sudo: required__ no longer is.  The __sudo__ command is now always available in Travis CI and there is no way to turn it off.

Travis CI: The sudo tag is now deprecated in Travis

---

transcrypt/modules/org/transcrypt/__core__.js

I am having some issues trying to use Transcrypt with Ember.js.
So the way the bug works is that Ember [modifies the Function prototype](https://github.com/emberjs/ember.js/blob/d6352a54c068354da93bcb26a5df4c7ef9153ea7/packages/ember-runtime/lib/ext/function.js#L76). When this happens, the newly created `cls` inherits all of the attributes attached to the Function prototype. During the `for (var attrib in base)` loop, these inherited attributes show up. But since they were applied directly to the prototype object instead of by using `defineProperty`, `getOwnPropertyDescriptor` returns `null`. This then fails during the call to `defineProperty`, saying that the descriptor must not be null.
I know this use case is a little bit niche, but I was wondering if you would consider this fix, or if …

Fixing compatibility issue with Ember.js

---

transcrypt/development/automated_tests/transcrypt/control_structures/__init__.py
transcrypt/modules/org/transcrypt/compiler.py

The previous implementation would call the body of `with` multiple times, if it contains multiple context managers.
For example, for the following code:
```
with a, b:
fn()
```
would be generated the equivalent of this:
```
with a:
fn()
with b:
fn()
```

Fix `with` statement for multiple context managers

---

transcrypt/modules/org/transcrypt/compiler.py

Preliminary implementation of #552, placed here to get some feedback.
I've managed to make it work for the most of the pragmas, including 'skip' and 'alias'. The `__exit__` part of the `with` statement is implemented by prefixing `no` to the name of pragma (or removing it) for now, which should work well in most cases, but it will not always restore the flags to the same state they were before `with`. There is various ways to go about this problem.
I think, the simplest solution would be to write a pair of push/pop methods (and push/pop pragmas, probably) to save and restore all flags at once and use them before and after with-clause. This will have side effect of creating a scope for pragmas inside each with-clause, but the effect is probably not undesired.

[WIP] __pragma__ as context manager

---

.travis.yml

Also, __Xenial__ is now Travis CI's default distro.

Travis CI: Run parallel test on Python 3.8

---

transcrypt/development/automated_tests/transcrypt/module_builtin/__init__.py
transcrypt/modules/org/transcrypt/__builtin__.js

Add `start` argument to `enumerate` function in _\_\_builtin\_\_.js_
Add autotests for `enumerate` function to _module_builtin_
Fixes issue https://github.com/QQuick/Transcrypt/issues/804

Add start argument to builtin enumerate function to match CPython
